### ISSUE TITLE
Rugby Scoreboard Review

### ISSUE THREAD

**Issue by JRC404** [sjweeks/rugbyScoreBoard#1]
The styling for the CSS is very nice, very clean. 

You have added statistics to the game, which is very good. You can tidy up a few things:

1. An ability to stop at half-time.
2. Ability to input team names.
3. A scroll inside of the div, so the page doesn't get longer. 
4. A time stamp for events

A really good project.

**Comment by sjweeks** [comment]
1, 3 & 4 have all been completed. Just working on the input team names part :)

**Comment by sjweeks** [comment]
All four done :)
